apiVersion: v1
kind: Service
metadata:
  name: boston-house-price-predictor-svc
  labels:
    app: boston-house-price-predictor
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30002
    targetPort: 80
    protocol: TCP
  selector:
    app: boston-house-price-predictor